### ISSUE TITLE
Page Up/Down indicators

### ISSUE THREAD

**Issue by suzannezc** [wrdsb/cosmos#708]
Google Groups view, Version 20.38

GUI for page up/down is hard to find and appears in context of the content instead of context of the interface.

(under search field, and under content, within the box, left aligned)

<img width="806" alt="Screen Shot 2020-09-22 at 11 48 21 AM" src="https://user-images.githubusercontent.com/6463808/93906046-b3990f00-fcc9-11ea-828b-150be5e2e2e9.png">

**Comment by suzannezc** [comment]
Last page/first page indicators would be grand, too.

**Comment by jschumann** [comment]
Redesigned entire interface. Issue resolved.
